### ISSUE TITLE
Split nsz files not recognized through usb

### ISSUE THREAD

**Issue by JasonCT25** [blawar/goldbricks#4]
I can't install split nsz files through usb. I can drag the exact same file onto my sd card and install it from my sd card, but if I locate the file from usb mode then it won't let me install it. It says it's an nsp package or something. It shows up as 0 bytes too

**Comment by blawar** [comment]
split files from PC side are not supported.  Just install the full size NSZ

**Comment by Aliasim800** [comment]
How did you split the nsz file? What did you use to do it?
