### ISSUE TITLE
Insufficient Memory

### ISSUE THREAD

**Issue by Roulio78** [blawar/goldbricks#5]
I can't install NSZ or NSP files. It says "Unsufficient Memory", "Due to unoptimized code, GoldBricks requires more memory to run. Please run this application using title override or a NSP forwarder"

**Comment by ELY3M** [comment]
you need to hold R and you tap one of your games for full RAM.

**Comment by McLolz** [comment]
> I can't install NSZ or NSP files. It says "Unsufficient Memory", "Due to unoptimized code, GoldBricks requires more memory to run. Please run this application using title override or a NSP forwarder"

I have the same error.
![IMG_20191204_205401](https://user-images.githubusercontent.com/23122845/70205270-61561580-16d8-11ea-82a2-6611f3ba1f63.jpg)

**Comment by blawar** [comment]
install the forwarder or hold r when launching the title to get high memory mode.
